### ISSUE TITLE
Graceful shutdown for FuseQuery

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/datafuse#832]
**Summary**
- [x] MySQL Handler [#704]
- [x] ClickHouse Handler [#931]
- [x] Metric API Service [#863]
- [x] HTTP API Service [#854]
- [x] RPC API Service [#931]
